#ifndef __SMARTHOME_H_
#define __SMARTHOME_H_
#define ENDPOINT_ID_SMARTHOME 0X01
#define PROFILE_ID_SMARTHOME 0X501
#define DEVICE_ID_COORDINATOR 0X01
#define DEVICE_ID_LEDDEVICE 0X02
#define DEVIDE_VERSION_ID 0X0

#define LEDJOINNET_CMD_ID 0X1
#define TOGGLE_LED_CMD_ID  0X2
#define HEART_BEAT_CMD_ID  0X3
#define DHT11VALUE_CMD_ID 0X4
#define RC522VALUE_CMD_ID 0X5
#define RC522bVALUE_CMD_ID 0X6
#define  HEART_BEAT_MAX_COUNT 3


#define TIMER_TIMEOUT_EVT 0X01
#define DHT11_PERIOD_EVT 0x02
#define RC522_PERIOD_EVT 0x03
#define RC522b_PERIOD_EVT 0x04
#endif